payment-service:
  image: payment-service:latest
  build: ./payment-service
  ports:
    - "8082:8082"
  environment:
    - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
    - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
    - PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET}